server:
  port: 8080
eureka: 
   client: 
      serviceUrl: 
         #defaultZone: http://7fb6b1eda5c4445eaf6a.eastus.aksapp.io/eureka 
         defaultZone: http://localhost:8081/eureka  
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
      - id: customer-service
        uri: http://localhost:8082/
        predicates:
        - Path=/ customers/v1/**
      - id: restaurant-service
        uri: http://localhost:8083/
        predicates:
        - Path=/restaurants/v1/**
      - id: order-service
        uri: http://localhost:8084/
        predicates:
        - Path=/orders/v1/**
      - id: driver-service
        uri: http://localhost:8085/
        predicates:
        - Path=/ drivers/v1/**
      - id: search-service
        uri: http://localhost:8086/
        predicates:
        - Path=/search/v1/**
      - id: invoice-service
        uri: http://localhost:8087/
        predicates:
        - Path=/ invoices/v1/**