server:
  port: 8087
spring:
  application:
    name: invoice-service  
fileBaseLocation: D:/HCL/invoiceReport_ 
eureka: 
   client: 
      serviceUrl: 
         #defaultZone: http://7fb6b1eda5c4445eaf6a.eastus.aksapp.io/eureka 
         defaultZone: http://localhost:8081/eureka    